image: node:latest

stages:
  - build
  - deploy

variables:
  NODE_ENV: "development"

build:
  stage: build
  script:
    - "echo \"[stage: build] building web root\""
    - echo $PRIVATE_JS_BODY > src/config/private.js
    - yarn install --production=false
    - yarn build-web
  artifacts:
    paths:
      - build/
      - src/ # to be able to check the private.js vars

deploy_staging:
  stage: deploy
  environment:
    name: staging
    url: https://dgmd-e60-staging.herokuapp.com
  script:
    - "echo \"[stage: deploy] deploying to staging\""
    - "echo \"[stage: deploy] frehsen dpl\""
    - apt-get update -qy
    - apt-get install -y ruby-dev rubygems
    - gem install dpl
    - "echo \"[stage: deploy] deploy to heroku staging: dgmd-e60-staging\""
    - dpl --provider=heroku --app=dgmd-e60-staging --api-key=$HEROKU_API_KEY --skip-cleanup
  only:
    - master
    - staging

deploy_production:
  stage: deploy
  environment:
    name: production
    url: http://123-aprende.selfenrichment.online
  script:
    - "echo \"[stage: deploy] deploying to PRODUCTION\""
    - "echo \"[stage: deploy] frehsen dpl\""
    - apt-get update -qy
    - apt-get install -y ruby-dev rubygems
    - gem install dpl
    - "echo \"[stage: deploy] deploy to heroku PRODUCTION: dgmd-e60\""
    - dpl --provider=heroku --app=dgmd-e60 --api-key=$HEROKU_API_KEY --skip-cleanup
  when: manual
  only:
    - master
